### ISSUE TITLE
English translation for documentation

### ISSUE THREAD

**Issue by CxrlosKenobi** [esyede/rakit#12]
### Deskripsi
To keep growing and reach a lot of users in GitHub it is highly recommended to keep a documentation translated to English at least. Would be very useful guys!

### Info tambahan

  - Versi rakit: NaN for documentation
  - Versi php: NaN for documentation
  - Webserver: NaN for documentation

**Comment by esyede** [comment]
Moved to [#4](https://github.com/esyede/rakit/issues/4)
