### ISSUE TITLE
Dokumentasi

### ISSUE THREAD

**Issue by andifahruddinakas** [esyede/rakit#16]
### Deskripsi
Link dokumentasi di website https://rakit.esyede.my.id bermasalah tapi yang offline normal.

Saya bandingkan dengan yang offline
https://rakit.esyede.my.id/index.php/docs/install#kebutuhan-sistem
Harusnya
https://rakit.esyede.my.id/index.php/docs/id/install#kebutuhan-sistem atau
https://rakit.esyede.my.id/index.php/docs/en/install#kebutuhan-sistem (sesuai pilihan bahasa, di web tsb tdk ada pilihan bahsa)

### Info tambahan

  - Versi rakit: v0.9.9
  - Versi php: 7.4
  - Webserver: Apache

**Comment by esyede** [comment]
Fixed in 1f6d6d4e3bae51901c3fb39a065df1493d249fab
