### ISSUE TITLE
Invalid Access package URL

### ISSUE THREAD

**Issue by reidsneo** [esyede/rakit#22]
### Deskripsi
Access package was downloaded from wrong URL
![image](https://user-images.githubusercontent.com/12298979/182825902-9b505295-1e64-4756-96b0-b4883035195c.png)
I tried to debug it going to archive path instead
![image](https://user-images.githubusercontent.com/12298979/182826025-c68b8f69-c8de-4b76-90ae-681dc96e099a.png)

### Info tambahan

  - Versi rakit: - 0.99
  - Versi php: - 7.4 25
  - Webserver: - PHP Serve

**Comment by esyede** [comment]
Thanks for reporting! Looks like github being inconsitance with their zipball links. Fixed.
