### ISSUE TITLE
how using many to many polymorphic?

### ISSUE THREAD

**Issue by wznuhidayat** [esyede/rakit#32]
### Deskripsi

Cara menggunakan many to many polymorphic gmna bang?

### Info tambahan

  - Versi rakit: - 
  - Versi php: -
  - Webserver: -

**Comment by esyede** [comment]
@wznuhidayat
Coba gini mas:
https://rakit.esyede.my.id/docs/id/database/facile#many-to-many

**Comment by wznuhidayat** [comment]
> @wznuhidayat Coba gini mas: https://rakit.esyede.my.id/docs/id/database/facile#many-to-many

itu many to many biasa mas gk ada callable type nya

soalnya pada table relation saya seperti ini

id      - INTEGER
user_id - INTEGER
general_id - INTEGER
callable_type - STRING

dimana pada callable_typenya merujuk pada table yang merelasikanya..

ada gk ? 
klw gk ada, ada cara alternatifnya gk?

**Comment by esyede** [comment]
@wznuhidayat Belum ada sih mas.
Boleh liatin contoh datanya?

**Comment by wznuhidayat** [comment]
> @wznuhidayat Belum ada sih mas. Boleh liatin contoh datanya?

contoh saya punya table 3 table

User
id - INTEGER
name - STRING

Product 
id - INTEGER
name - STRING

Pictures
id - INTEGER
path - STRING
imageable_id - INTEGER
imageable_type - STRING


dari 3 table itu user maupun category bisa memiliki bayak gambar

**Comment by esyede** [comment]
> > @wznuhidayat Belum ada sih mas. Boleh liatin contoh datanya?
> 
> contoh saya punya table 3 table
> 
> User id - INTEGER name - STRING
> 
> Product id - INTEGER name - STRING
> 
> Pictures id - INTEGER path - STRING imageable_id - INTEGER imageable_type - STRING
> 
> dari 3 table itu user maupun category bisa memiliki bayak gambar


@wznuhidayat Oh, untuk skema pas insert ke tabel `users` atau tabel `products` juga perlu insert ke tabel `pictures` nya,

Misal `imageable_type` diisi string `'user'` pas yang insert adalah tabel users, dan diisi `'product'` ketika yg insert adalah tabel products. Kemudian untuk retrieve datanya bisa buat method custom di modelnya dengan 2 parameter seperti berikut:
```php
public function images($id, $imageable_type)
{
    return $this->where('id', $id)->where('imageable_type', $imageable_type);
}
```

**Comment by wznuhidayat** [comment]
> > > @wznuhidayat Belum ada sih mas. Boleh liatin contoh datanya?
> > 
> > 
> > contoh saya punya table 3 table
> > User id - INTEGER name - STRING
> > Product id - INTEGER name - STRING
> > Pictures id - INTEGER path - STRING imageable_id - INTEGER imageable_type - STRING
> > dari 3 table itu user maupun category bisa memiliki bayak gambar
> 
> @wznuhidayat Oh, untuk skema pas insert ke tabel `users` atau tabel `products` juga perlu insert ke tabel `pictures` nya,
> 
> Misal `imageable_type` diisi string `'user'` pas yang insert adalah tabel users, dan diisi `'product'` ketika yg insert adalah tabel products. Kemudian untuk retrieve datanya bisa buat method custom di modelnya dengan 2 parameter seperti berikut:
> 
> ```
> public function images($id, $imageable_type)
> {
>     return $this->where('id', $id)->where('imageable_type', $imageable_type);
> }
> ```

terus klw seperti itu cara saya mengambil datanya pada eager loading gmna mas? kan pada eager loading with() kita tidak bisa passing parameter?

minta personal contactnya mas biar lebih enak hehe..

**Comment by esyede** [comment]
@wznuhidayat 
> minta personal contactnya mas biar lebih enak hehe..

Tidak bisa di eagerload mas, harus diambil manual karena memang belum ada fiturnya

> minta personal contactnya mas biar lebih enak hehe..

Bisa cek disini ya mas https://esyede.my.id
