### ISSUE TITLE
[Improvement] Database select statement must using array instead plain select separated by comma

### ISSUE THREAD

**Issue by reidsneo** [esyede/rakit#5]
### Deskripsi
Current Database selection cannot handle multiple field selection automatically to array
```
Schema::table('users', function ($table) {
        $table->create();
        $table->increments('id');
        $table->string('username');
        $table->string('email');
        $table->string('phone')->nullable();
        $table->text('about');
        $table->timestamps();
    });

    DB::table('users')
    ->insert(['email' => 'example1@gmail.com']);
    DB::table('users')
    ->insert(['email' => 'example2@gmail.com']);

    $user = DB::table('users')->select('id','email')->get(); //ISSUE only return id
    $user = DB::table('users')->select(['id','email'])->get(); //OKAY return both id and email
    dd($user);
```

Fixes :
https://github.com/esyede/rakit/blob/83ec74bc26679783e586e89e0f1deb8cd06d1c4b/system/database/query.php#L148

Replace with : 
`$this->selects = is_array($columns) ? $columns : func_get_args();
`

References : [https://laravel.com/docs/8.x/queries](url)

### Info tambahan

  - Versi rakit: - v0.9.8
  - Versi php: - 7.4.12
  - Webserver: - PHP 7.4.12 Development Server

**Comment by esyede** [comment]
Done 93254617281312e83f0ffb27fb7e61cb262b5700
